version: '2'
services:
  elastic:
    image: elasticsearch:2.4.6
    hostname: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#bin/magento config:set catalog/search/engine elasticsearch5
#bin/magento config:set catalog/search/elasticsearch5_server_hostname elastic
#bin/magento indexer:reindex catalogsearch_fulltext