version: '2'
services:
  app:
    extends:
      file: ./php.yml
      service: app
    build:
      context: ..
      dockerfile: build/php/perf
    image: magento_app:perf_${PHP_VERSION}
    volumes:
      - ../etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
