version: '2'
services:
  proxy:
    image: million12/varnish
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ../etc/varnish/varnish.vcl:/etc/varnish/default.vcl:ro
  web:
    depends_on:
      - app
    expose:
      - "8080"
    volumes:
      - ../etc/varnish/nginx.conf:/etc/nginx/nginx.conf:ro
