version: '2'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
  db:
    image: duhon/magento_db:2.1.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "magento"
  app:
    image: duhon/magento_app:2.1.0.rc
    volumes_from:
      - db
